image:
  file: Dockerfile
tasks:
- init: npm install
  command: npm start
ports:
- port: 3000
  onOpen: open-browser
vscode:
  extensions:
    - edukera.archetype@0.41.0
    - baking-bad.michelson@0.1.0
